# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Human Design 
  
author: Nik Polonsky
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "/whiteglass-template" # the subpath of your site, e.g. /blog
url: "https://nikpolonsky.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""

# lang: en
timezone: UTC

# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:
comments: false

social_media:
  telegram:
    id: 'tov_nixon'
    href: 'https://t.me/'
    title: 'Telegram'
    fa-icon: 'fa-telegram-plane'

  whatsapp:
    id: '4917642728553'
    href: 'https://wa.me/'
    title: 'Whatsapp'
    fa-icon: 'fa-square-whatsapp'

  instagram:
    id: 'tov_nixon'
    href: 'https://instagram.com/'
    title: 'Instagram'
    fa-icon: 'fa-instagram-square'

# Build settings
theme: jekyll-whiteglass
plugins:
  - jekyll-polyglot
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  
exclude:
  - README.md
  - vendor/

# Outputting
permalink: /:year/:month/:day/:title/

# Markdown settings
markdown: kramdown
excerpt_separator: "<!-- more -->"
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# jekyll-paginate
paginate_path: /posts/:num/
paginate: 5

#Polyglot
languages: ["en", "ua", "ru"]
default_lang: "ua"
enabled: true
translate_urls: true
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

#Data
human_design_title:
  en: "Nik Polonsky"
  ua: "Нік Полонський"
  ru: "Ник Полонский"

blog_archive_title:
  en: "Blog"
  ua: "Блог"
  ru: "Блог"
